format = """
╭─[░▒▓](#a3aed2)\
[ ⮝ ](bg:#a3aed2 fg:#090c0c)\
[](bg:#614847 fg:#a3aed2)\
$directory\
[](fg:#614847 bg:#4a393a)\
$git_branch\
$git_status\
[](fg:#4a393a bg:#291f20)\
$nodejs\
$python\
$rust\
$golang\
$php\
[](fg:#291f20 bg:#0a0708)\
$time\
[ ](fg:#0a0708)\
$fill\
[](#614847)\
$cmd_duration\
\n╰───$character"""

[directory]
style = "fg:#e3e5e5 bg:#614847"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#4a393a"
format = '[[ $symbol $branch ](fg:#614847 bg:#4a393a)]($style)'

[git_status]
style = "bg:#4a393a"
format = '[[($all_status$ahead_behind )](fg:#614847 bg:#4a393a)]($style)'

[nodejs]
symbol = ""
style = "bg:#291f20"
format = '[[ $symbol ($version) ](fg:#614847 bg:#291f20)]($style)'

[python]
symbol = ""
style = "bg:#291f20"
format = '[[ $symbol ($version) ](fg:#614847 bg:#291f20)]($style)'

[rust]
symbol = ""
style = "bg:#291f20"
format = '[[ $symbol ($version) ](fg:#614847 bg:#291f20)]($style)'

[golang]
symbol = ""
style = "bg:#291f20"
format = '[[ $symbol ($version) ](fg:#614847 bg:#291f20)]($style)'

[php]
symbol = ""
style = "bg:#291f20"
format = '[[ $symbol ($version) ](fg:#614847 bg:#291f20)]($style)'

[fill]
symbol = " "

[cmd_duration]
min_time = 0
format = "[ $duration ](fg:#e3e5e5 bg:#614847)"

[time]
disabled = true
time_format = "%R"
style = "bg:#0a0708"
format = '[[  $time ](fg:#a0a9cb bg:#0a0708)]($style)'
